### PR TITLE
Add Option to Choose Shop Indicator Displayed Information

### PR DESCRIPTION
**Pull request by BenMiller3**
Screenshot 2023-06-28 at 3 33 46 PM

Closes Issue: https://github.com/2dos/DK64-Randomizer/issues/1432

Shop indicator change: https://github.com/2dos/DK64-Randomizer/pull/984/files#diff-02d0ce94bc4be4990894a2576aea7c5565217d0391cd72a8ac39dd6523433c81 

| No Display  | Kong-Only | Kong and Item |
| ------------- | ------------- | ------------- |
|  |  
kong-only
|  |

### CODE REVIEW

**Comment by 2dos** [comment]
Moving PR to Dev instead of PRD. We will review and reach out if we have questions.

**Comment by theballaam96** [comment]
Hello Ben,
Welcome to contributing to DK64 Randomizer. It's good to see people interested in helping out with this project.
The dev team have had some time to review your PR and we have some changes that we would like you to address before we consider merging this into dev or the post-2.0 branch.

- The patching procedure hasn't been updated to recognize that the `spoiler.settings.shop_indicator` variable is non-boolean. If you take a look at line 182 in `randomizer/Patching/ApplyRandomizer.py`, you'll see where it's adding this class instance, and it's setting the target to 2. Lower down (Line 190 -> 193), it'll set the location in ROM to 2 if the variable is non-zero. As such, your changes won't actually be fed correctly to ROM.
I would suggest removing line 182 (since it's no longer boolean), and adding this section of code somewhere below (wherever you see fit)
```
LocalROM().seek(sav + 0x134)
LocalROM().write(int(spoiler.settings.shop_indicator))
```
- I see in your screenshots and from your code that you've added a dropdown for this, but you haven't removed the toggle. I don't think it would be good for the UI to have two separate things which control the same variable. I would suggest removing the toggle as this is no longer necessary.
- I see in some of your recent changes you are changing stuff with the base hack, but I'm not sure why you're doing this. I guess the attribute name `shop_indicator_on` isn't the best given the changes you are making, but nothing else needs to be touched in the base hack. I would suggest reverting the changes to the base hack (with exception to the attribute name change).
However, for future reference (since the attribute change won't affect the base hack), the way the base hack infrastructure works is that rather than compiling the C code whenever a user makes a seed, there's a BPS patch made (and a couple other related things) that the site can use to patch in all the C code. As such, this requires the bps to be updated upon every change to the base hack. With a command prompt, if you navigate to the `base-hack` directory, and run `./build.bat - python` (replacing `python` with `python3` if you're using python3 instead), it'll rebuild the base hack BPS and associated files. I know you've joined the discord recently, and I know the base hack stuff takes a bit of setting up, so let me know if you have any questions on this.

**Other notes that don't need changes to the code you've written**
- I see you're using Jetbrains instead of VSCode. We have a list of tasks that we run in VSCode to make sure things lint correctly. If you go to `.vscode/tasks.json`, and take a look at the tasks run with `Lint Repo`, those will need to be run before pushes to make sure that the linter we use likes your changes. I'm not entirely sure how you'd get to automating this with Jetbrains, so it's something for you to look into.
- The changes here, since it's changing the amount of bits needed for the `shop_indicator` settings variable (from 1 to 2), will almost certainly break existing settings strings, including the presets. We might need to shuffle around some things, but this *might* mean this is pushed back to 2.1 rather than being included in 2.0 (As such, being merged into the post-v2 branch rather than dev).

Feel free to ask questions

**Comment by BenMiller3** [comment]
> Hello Ben, Welcome to contributing to DK64 Randomizer. It's good to see people interested in helping out with this project. The dev team have had some time to review your PR and we have some changes that we would like you to address before we consider merging this into dev or the post-2.0 branch.
> 
> * The patching procedure hasn't been updated to recognize that the `spoiler.settings.shop_indicator` variable is non-boolean. If you take a look at line 182 in `randomizer/Patching/ApplyRandomizer.py`, you'll see where it's adding this class instance, and it's setting the target to 2. Lower down (Line 190 -> 193), it'll set the location in ROM to 2 if the variable is non-zero. As such, your changes won't actually be fed correctly to ROM.
>   I would suggest removing line 182 (since it's no longer boolean), and adding this section of code somewhere below (wherever you see fit)
> 
> ```
> LocalROM().seek(sav + 0x134)
> LocalROM().write(int(spoiler.settings.shop_indicator))
> ```
> 
> * I see in your screenshots and from your code that you've added a dropdown for this, but you haven't removed the toggle. I don't think it would be good for the UI to have two separate things which control the same variable. I would suggest removing the toggle as this is no longer necessary.
> * I see in some of your recent changes you are changing stuff with the base hack, but I'm not sure why you're doing this. I guess the attribute name `shop_indicator_on` isn't the best given the changes you are making, but nothing else needs to be touched in the base hack. I would suggest reverting the changes to the base hack (with exception to the attribute name change).
>   However, for future reference (since the attribute name change won't affect the base hack), the way the base hack infrastructure works is that rather than compiling the C code whenever a user makes a seed, there's a BPS patch made (and a couple other related things) that the site can use to patch in all the C code. As such, this requires the bps to be updated upon every change to the base hack. With a command prompt, if you navigate to the `base-hack` directory, and run `./build.bat - python` (replacing `python` with `python3` if you're using python3 instead), it'll rebuild the base hack BPS and associated files. I know you've joined the discord recently, and I know the base hack stuff takes a bit of setting up, so let me know if you have any questions on this.
> 
> **Other notes that don't need changes to the code you've written**
> 
> * I see you're using Jetbrains instead of VSCode. We have a list of tasks that we run in VSCode to make sure things lint correctly. If you go to `.vscode/tasks.json`, and take a look at the tasks run with `Lint Repo`, those will need to be run before pushes to make sure that the linter we use likes your changes. I'm not entirely sure how you'd get to automating this with Jetbrains, so it's something for you to look into.
> * The changes here, since it's changing the amount of bits needed for the `shop_indicator` settings variable (from 1 to 2), will almost certainly break existing settings strings, including the presets. We might need to shuffle around some things, but this _might_ mean this is pushed back to 2.1 rather than being included in 2.0 (As such, being merged into the post-v2 branch rather than dev).
> 
> Feel free to ask questions

Thanks so much for the thorough review and explanation! I've made the updates and was able to test with the Kong only situation and that worked (screenshot attached). I'll put more screenshots of the updated UI and other test cases early next week. Appreciate the assistance on this.

**Comment by theballaam96** [comment]
Thanks Ben, will take a look into it in the coming days

**Comment by theballaam96** [comment]
Hello Ben,
Thanks for your updates on this. This *mostly* looks fine, but there's a few things we've spotted that we'd like changed before pushing to some development branch
- I see you've changed `shop_indicator_on` to `shop_indicator` in `variable_space_structs.h`. This change we're fine with, however, we see that you haven't changed this anywhere else in the c code, which would cause a build error whenever someone tries to rebuild the base hack with your changes. This is referenced on lines 441 and 442 in `./base-hack/src/misc/shop_indicator.c`
- Your change to `README.md` doesn't have the correct indentation, implying that the shop indicator change is part of fast start. We've mentioned internally in the dev channel that we really need to update the README as it hasn't been updated since 1.0. That's something we'll address for 2.1. In the meanwhile, add it as item 12 instead of part of item 11. You can see the markdown preview of how it will look here: https://github.com/BenMiller3/DK64-Randomizer/blob/shopindicator/shopindicator_ui/README.md
- I don't think this was intended, but your changes alter `package.json` and `.DS_Store`. I'd advise removing these changes from your PR as there is no reason to modify these files with your changes.

**Comment by theballaam96** [comment]
Will need a response in the next week on this otherwise this PR will be closed.

**Comment by theballaam96** [comment]
Closing due to inactivity. If you wish to work on this change further, feel free to submit a PR with those changes in future.

Kind Regards,
DK64R Dev Team

**Pull request closed without merging**
