### PR TITLE
Adding different weights for random settings

### PR DESCRIPTION
**Pull request by TheSoundDefense**
There are now three difficulty options for randomizing settings.

### CODE REVIEW

**Comment by theballaam96** [comment]
Not sure I get the logic behind Boulder clips being weighted 0, but TBS and Phasewalking being weighted 5% on the glitch logic selector?

**Comment by TheSoundDefense** [comment]
I am pulling some of these numbers out of nowhere, please give feedback. Should all of them be set to 0 or something else?

**Comment by theballaam96** [comment]
In terms of order of difficulty (with a rating of difficulty out of 10):
1/10: Adv Platforming, B Locker Skips, Phase Swimming

2/10: T&S Skips, Boulder Clips, Swim Through Shores

3/10: Moonkicks (Trick is like a 2/10, but there's some rough scenarios like Rotating Room kick which make this harder), Ledge Clips, Skew

5/10: General Clips (This one is hard to judge. A lot of variance in difficulty with the tricks here). Most of the problem with this one is just knowing the tricks

8/10: Spawn Snags (Some are easy. Lots of convoluted setups though)

10/10: TBS, Phasewalking (Phasewalking as a trick is a fair bit easier, probably closer to a 6/10. However, the sheer amount of phasewalks which are required bc how much pw breaks logic make this a 10/10).

**Comment by TheSoundDefense** [comment]
Thanks for the breakdown. I never see people do glitched logic so I wasn't sure what was more difficult. I've adjusted the chances accordingly.

**Comment by theballaam96** [comment]
There's also an argument to be made for AP to be the only "glitch" to be allowed for hard mode. Glitches/no logic is a rough setting.

Glitch logic is a lot of what you know rather than taking on an unexpected scenario. If you don't know moonkicks, you can't think out how to come up with the moonkick glitch to attack this.

No logic is worse, cause it's just a random chance that your seed is unbeatable

**Comment by TheSoundDefense** [comment]
Hm that is fair. I was thinking of difficult being an "anything is possible" setting, but I don't want to make seeds actually impossible unless you've deeply studied glitches or anything.

So based on that suggestion, I would change "glitch logic" to a 20% chance, and if you roll glitch logic, AP is always required but no other glitch is. And maybe we just turn off no logic for all difficulties?

**Comment by theballaam96** [comment]
Agreed on that suggestion and the proposition of removing any chance of no logic with random settings.

**Comment by TheSoundDefense** [comment]
Thanks for the feedback! That change has been made.

**Comment by theballaam96** [comment]
PR looks good, won't be merging until Wednesday. Keiper has a GDQ run which is running off 2.1 on Tuesday and we want to keep 2.1 stable beyond reasonable doubt until then. We're only merging fixes which are urgent until Tuesday

**Review by theballaam96 — APPROVED** [review]

**Pull request merged**
