### PR TITLE
October 2023 plandomizer updates

### PR DESCRIPTION
**Pull request by TheSoundDefense**
- An "Introduction" page has been added. This will offer some basic information and resources for making plando seeds.
- Validation check: a single shop can't have an item for All Kongs and also for an individual Kong.
- Validation check: if the user is using fixed hints, we cannot have more than five plandomized hints.
- Enemy drops are sorted into their own subcategories on each page, to make the UI a little cleaner.
- Titles are now capitalized automatically in CSS, by default.
- We now enforce a limit of 100 junk items.
- Junk items cannot be assigned to crates or enemy drops.

### CODE REVIEW

**Comment by theballaam96** [comment]
Lint failed on this. Please run the `Lint Repo` task on VSCode

**Comment by pbeierle22** [comment]
I don't see a need for the 100 junk cap. With dropsanity on you will easily clear 100 junk items. I think this one's a "buyer beware" kinda situation. Users already need to know logic pretty well.

**Comment by theballaam96** [comment]
Its a technical cap rather than a gameplay cap. I've allocated 100 flags for it. Placing more than 100 would make junk items use flags it shouldn't

**Comment by theballaam96** [comment]
Does this PR prohibit junk items being on enemies or melon crates? Whilst them being on enemies/melon crates doesn't break anything, it does take up valuable junk items (esp if dropsanity is on) given the experience isn't too dissimilar whether it's a junk item or a no item. We have it prohibited in non-plando, so just curious if that's the same for plando too.

**Comment by TheSoundDefense** [comment]
I just edited the PR to prevent junk items being added in those places. I also added type hints and made a couple of other minor fixes.

**Review by theballaam96 — APPROVED** [review]

**Pull request merged**
